apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespaces.yaml
  - services.yaml
  - orchestration-api-deployment.yaml
  - orchestration-supervisor-deployment.yaml
  - execution-runners-deployments.yaml
  - networkpolicy.yaml

configMapGenerator:
  - name: execution-capability-catalog
    files:
      - execution-capability-catalog.json=execution-capability-catalog.json

generatorOptions:
  disableNameSuffixHash: true
