apiVersion: v1
kind: Namespace
metadata:
  name: artbattle-orchestration
  labels:
    plane: orchestration
---
apiVersion: v1
kind: Namespace
metadata:
  name: artbattle-execution
  labels:
    plane: execution
