apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: replicas.yaml

images:
  - name: ghcr.io/your-org/employee-slackbot
    newTag: prod
  - name: ghcr.io/your-org/employee-mcp-gateway
    newTag: prod
